[package]
name = "gpt-function-call-demo"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
async-openai-wasi = "0.16.2"
chrono = "0.4.31"
dotenv = "0.15.0"
serde_json = "1"
slack-flows = "0.3.4"
tokio_wasi = { version = "1.25.0", features = ["fs", "macros"] }
serde = {version = "1", features = ["derive"]}
http_req_wasi = "0.11.1"
web-scraper-flows = "0.1.0"
flowsnet-platform-sdk = "0.1.6"
log = "0.4.20"
store-flows = "0.3.1"
lazy_static = "1.4.0"
once_cell = "1.18.0"
